Support for group-tab and code-tab in Markdown #71
executablebooks/sphinx-tabs pull request #79
Opened 2020-08-17 18:16 UTC by foster999

Major refactor of tabs, group-tabs and code-tabs

Removes hard-coded reStructuredText for group and code tabs

2020-08-17 18:17 UTC, foster999 commented
May need further work to meet tests

2020-08-17 18:18 UTC, chrisjsewell commented
well that was quick lol

2020-08-18 09:00 UTC, foster999 commented on sphinx_tabs/tabs.py
> +            LEXER_MAP[short_name] = "R"
Will drop this, as changes below allow you to specify the `code-tab` label to override the pygments names

2020-08-18 09:02 UTC, foster999 commented on sphinx_tabs/tabs.py
> +            del self.tab_id
Looking back, I don't think we need to delete these attrs after use
```suggestion
```

2020-08-18 09:03 UTC, foster999 commented on sphinx_tabs/tabs.py
> +            del self.tab_classes
```suggestion
```

2020-08-18 09:07 UTC, foster999 commented
> Just wait for #76 to be merged, then we can see the damage

Sounds good to me, thanks!

2020-09-03 21:27 UTC, foster999 commented
My output HTML seems to have lost its indentation, so the XML is no longer matching. @chrisjsewell any idea where/how the indentation is determined?

2020-09-03 21:32 UTC, chrisjsewell commented
This test suite is a legacy thing I'm afraid, I haven't touched it.
If/when I do any more work on this repo, I would look to rewrite it with similar pytest fixtures as used in myst-parser, etc

2020-09-03 21:34 UTC, chrisjsewell commented
obviously you're welcome to give it a go yourself 😬

2020-09-03 22:15 UTC, foster999 commented
Yeah I might have a stab at moving the tests over to pytest... no promises though :sweat_smile:

My question above was actually a general sphinx one - do you know how sphinx determines HTML indentation? I presumed it would just indent with each node level, but the HTML sections from my code here have no indentation at all. I'm not sure what I've broken essentially

2020-09-03 22:18 UTC, chrisjsewell commented
Don't know, but in myst-parser etc I use beatifulsoup to prettify the HTML before diffing with pytest-regressions, which a) standardises the HTML and b) provides better error feedback

2020-09-03 22:24 UTC, foster999 commented
Thanks, that'll be really useful! `AssertionError: XML does not match` here isn't the most informative feedback

2020-09-06 19:31 UTC, foster999 commented
Ready to go after #88

2020-09-07 10:43 UTC, chrisjsewell requested changes
conficts to resolve 😬

2020-09-07 19:45 UTC, foster999 commented
Sorted 😄

2020-09-07 21:18 UTC, foster999 commented
Bonus to close #34

2020-09-09 08:08 UTC, chrisjsewell approved these changes
Cheers! well the tests pass, and I don't see any obvious errors, so 🤞 this doesn't open up any unexpected issues

2020-09-09 08:12 UTC, merged